name: 'xitara.faq::lang.faq.label'
modelClass: Xitara\Faq\Models\Faq
form: $/xitara/faq/models/faq/fields.yaml
defaultRedirect: xitara/faq/faq
create:
    title: 'xitara.faq::lang.faq.create_title'
    redirect: 'xitara/faq/faq/update/:id'
    redirectClose: xitara/faq/faq
update:
    title: 'xitara.faq::lang.faq.update_title'
    redirect: xitara/faq/faq
    redirectClose: xitara/faq/faq
preview:
    title: 'xitara.faq::lang.faq.preview_title'
