title: 'xitara.faq::lang.faq.list_title'
modelClass: Xitara\Faq\Models\Faq
list: $/xitara/faq/models/faq/columns.yaml
recordUrl: 'xitara/faq/faq/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
