name: 'xitara.pmfaq::lang.faq.label'
modelClass: Xitara\PMFaq\Models\Faq
form: $/xitara/pmfaq/models/faq/fields.yaml
defaultRedirect: xitara/pmfaq/faq
create:
    title: 'xitara.pmfaq::lang.faq.create_title'
    redirect: 'xitara/pmfaq/faq/update/:id'
    redirectClose: xitara/pmfaq/faq
update:
    title: 'xitara.pmfaq::lang.faq.update_title'
    redirect: xitara/pmfaq/faq
    redirectClose: xitara/pmfaq/faq
preview:
    title: 'xitara.pmfaq::lang.faq.preview_title'
