# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: xitara.faq::lang.groups.label

# Model Form Field configuration
form: $/xitara/faq/models/groups/fields.yaml

# Model Class name
modelClass: Xitara\Faq\Models\Groups

# Default redirect location
defaultRedirect: xitara/faq/groups

# Create page
create:
    # title: xitara.faq::lang.group.create_title
    redirect: xitara/faq/groups/update/:id
    redirectClose: xitara/faq/groups

# Update page
update:
    # title: xitara.faq::lang.group.update_title
    redirect: xitara/faq/groups
    redirectClose: xitara/faq/groups

# Preview page
preview:
    # title: xitara.faq::lang.group.preview_title
